version: "3.8"
services:
  charitee:
    container_name: "charitee-backend"
    image: "charitee-express:latest"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=${SERVER_PORT}
    volumes:
        - .:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mongodb
  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb_data_container:/data/db

volumes:
    mongodb_data_container:
