name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true

    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true
    
    - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: eu.gcr.io
        project_id: charitee-project-dev-1
        image_name: charitee

    - uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      working-directory: terraform

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: terraform

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: terraform

    - name: Terraform Linter
      uses: notrenderfarm/tflint-action@v1.2
      with:
        directory: 'terraform'

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      if: github.event_name == 'pull_request'
      working-directory: terraform
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SERVICE_KEY }}
    
    - name: Google Cloud Run Redeploy
      run: |-
        gcloud run deploy charitee-service \
        --image eu.gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/charitee:latest \
        --region europe-west6
        --quiet